[package]
authors = ["Kevin Del Castillo <quebin31@gmail.com>"]
edition = "2018"
name = "libmtp"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.2.1"
libc = "0.2.77"
libmtp-sys = {version = "1.1.17-1", path = "./libmtp-sys"}
num-derive = "0.3.2"
num-traits = "0.2.12"
thiserror = "1.0.20"
